### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by LisaMieth** [LisaMieth/bushfire-api#1]
### Small issues

- [ ] Handle suburb name typos that get resolved (like 'Richm')
- [ ] Handle suburb names that cannot be resolved
- [ ] Handle fire district names that cannot be resolved
- [ ] Handle states that cannot be resolved 

### Large Todos
- [ ] Add support for WA, TAS, ACT
- [ ] Find solution for QLD, NT
